<?php
include_once("templates/admin/BeanEditorPage.php");
include_once("forms/AdminUserForm.php");
include_once("beans/AdminUsersBean.php");

class AdminUserEditorPage extends BeanEditorPage
{

    public function __construct()
    {
        parent::__construct();


        //$this->page->checkAccess(ROLE_ADMIN_USERS_MENU);

        $this->setBean(new AdminUsersBean());
        $this->setForm(new AdminUserForm());

    }

    public function initView()
    {
        parent::initView();

        $this->view->getForm()->getRenderer()->setAttribute("onSubmit", "return checkForm(this)");
    }

    protected function renderImpl()
    {
        parent::renderImpl(); // TODO: Change the autogenerated stub

        ?>
        <script type='text/javascript'>
            function toggleRoles() {
                var roles = $(".InputComponent[field='role']");
                var access = $(".InputComponent [name='access_level']");

                if (access.val() == "Full Access") {
                    roles.css("display", "none");
                } else {
                    roles.css("display", "");
                }
            }

            onPageLoad(function () {
                toggleRoles();
            });
        </script>
        <script type='text/javascript' src='<?php
        echo SPARK_LOCAL; ?>js/md5.js'></script>
        <script type='text/javascript'>
            function checkForm(frm) {
                try {

                    if (frm.pass.value.length > 0 || frm.pass1.value.length > 0) {
                        if (frm.pass.value != frm.pass1.value) {
                            throw "Passwords do not match";
                        }
                        if (frm.pass.value.length < 6) {
                            throw "Minimum password length is 6";
                        }
                    }

                    frm.password_hash.value = hex_md5(frm.pass.value);

                    frm.pass.value = "";
                    frm.pass1.value = "";
                    return true;

                } catch (e) {
                    alert(e);
                }
                return false;
            }
        </script>
        <?php
    }
}