<?php
include_once("templates/admin/AdminLogin.php");
include_once("input/DataInputFactory.php");
include_once("forms/processors/FormProcessor.php");
include_once("mailers/ForgotPasswordMailer.php");

class ForgotPasswordProcessor extends FormProcessor
{
    /**
     * @param InputForm $form
     * @return void
     * @throws Exception
     */
    protected function processImpl(InputForm $form) : void
    {
        parent::processImpl($form);

        $ub = new AdminUsersBean();

        $email = $form->getInput("email")->getValue();

        if (!$ub->emailExists($email)) {
            throw new Exception(tr("This email is not registered with us"));
        }

        $users = new AdminUsersBean();

        $random_pass = Authenticator::RandomToken(8);
        $fpm = new ForgotPasswordMailer($email, $random_pass, fullURL(ADMIN_LOCAL . "/login.php"));
        $db = DBConnections::Open();
        try {
            $db->transaction();

            $userID = $users->email2id($email);
            $update_row["password"] = md5($random_pass);
            $users->update($userID, $update_row, $db);

            $fpm->send();

            $db->commit();

        }
        catch (Exception $e) {
            $db->rollback();
            throw $e;
        }

    }
}

class AdminLoginForgotPassword extends AdminLogin
{
    protected InputForm $form;

    public function __construct()
    {
        parent::__construct();

        $this->page->setTitle(tr("Forgot Password"));
        $this->page->head()->addCSS(SPARK_LOCAL . "/css/LoginForm.css");

        $this->form = new InputForm();
        $this->form->addInput(DataInputFactory::Create(DataInputFactory::EMAIL, "email", "Input your registered email", 1));


    }


    public function initView()
    {

        $frend = new FormRenderer($this->form);
        $frend->getSubmitButton()->setContents("Send");
        $frend->setClassName("LoginFormRenderer");
        $frend->setCaption(SITE_TITLE . "<BR><small>" . tr("Administration") . "</small>");

        $this->view = $frend;

        $this->items()->append($this->view);
    }

    public function startRender(): void
    {
        $proc = new ForgotPasswordProcessor();

        $proc->process($this->form);

        if ($proc->getStatus() == IFormProcessor::STATUS_OK) {
            Session::SetAlert(tr("Your new password was sent to your email") . ": " . $this->form->getInput("email")->getValue());
            header("Location: login.php");
            exit;
        }
        else {
            Session::setAlert($proc->getMessage());
        }

        parent::startRender(); // TODO: Change the autogenerated stub
    }

}
