<?php
include_once("templates/admin/BeanListPage.php");
include_once("components/renderers/cells/BooleanCell.php");
include_once("components/renderers/cells/ImageCell.php");
include_once("components/renderers/cells/DateCell.php");
include_once("beans/DynamicPagesBean.php");

class DynamicPageList extends BeanListPage
{
    public function __construct()
    {
        parent::__construct();

        $this->setBean(new DynamicPagesBean());
        $this->setListFields(array($this->getBean()->key()=>"PageID", "position" => "#", "item_photo" => "Photo", "item_title" => "Title",
                                   "item_date" => "Date", "visible" => "Visible", "keywords" => "Keywords"));

    }

    protected bool $is_chooser = FALSE;
    protected string $chooser_return_url = "";

    public function isChooser() : bool
    {

        return $this->is_chooser;
    }

    public function getChooserReturnUrl() : string
    {
        return $this->chooser_return_url;
    }

    protected function initPageActions()
    {
        parent::initPageActions();

        if (isset($_GET["chooser"])) {

            $this->page->setName("Choose Dynamic Page");
            $this->is_chooser = TRUE;
            $this->chooser_return_url = base64_decode($_GET["chooser"]);
        }

    }

    protected function initViewActions(ActionCollection $act)
    {
        if (!$this->is_chooser) {
            parent::initViewActions($act); // TODO: Change the autogenerated stub
        }

        $act->append(Action::RowSeparator());
        $act->append(new Action("Photo Gallery", "gallery/list.php", array(new DataParameter($this->bean->key()))));

        if ($this->is_chooser) {
            $act->append(Action::RowSeparator());
            $act->append(
                new Action("Choose", $this->chooser_return_url,
                    array(
                        new DataParameter("page_id", $this->bean->key()),
                        //new URLParameter("page_class", get_class($this->bean))
                    )
                )
            );
        }
    }

    public function initView()
    {
        parent::initView();
        $ticr = new ImageCell();
        $ticr->setBean($this->bean);

        $this->view->getColumn("item_photo")->setCellRenderer($ticr);

        $this->view->getColumn("visible")->setCellRenderer(new BooleanCell("Yes", "No"));

        $this->view->getColumn( "item_date")->setCellRenderer(new DateCell());
    }

    protected function renderImpl(): void
    {
        parent::renderImpl(); // TODO: Change the autogenerated stub

        if (isset($_GET["chooser"])) unset($_GET["chooser"]);

    }
}
