<?php

class ObjectInputProcessor extends InputProcessor
{
    protected $object;

    public function __construct(DataInput $input, DataObject $object)
    {
        parent::__construct($input);

        $this->transact_mode = InputProcessor::TRANSACT_OBJECT;

        $this->object = $object;
        $this->object->setName($input->getName());
    }

    public function getObject()
    {
        return $this->object;
    }

    public function setTransactBean(DBTableBean $bean)
    {
        throw new Exception("Setting transaction bean is not supported");
    }

    public function getTransactBean(): ?DBTableBean
    {
        return NULL;
    }

    public function beforeCommit(BeanTransactor $transactor, DBDriver $db, string $item_key)
    {

    }

    public function afterCommit(BeanTransactor $transactor)
    {

    }

    public function transactValue(BeanTransactor $transactor)
    {
        if ($this->object->getValue()) {
            $transactor->appendValue($this->input->getName(), DBConnections::Get()->escape(serialize($this->object)));
        }
    }

    public function loadPostData(array &$data)
    {
        parent::loadPostData($data); // TODO: Change the autogenerated stub
        $this->object->setData($data);
    }

    public function loadBeanData(int $editID, DBTableBean $bean, array &$item_row)
    {
        if (!isset($item_row[$this->input->getName()])) return;

        $object = $item_row[$this->input->getName()];

        $object = @unserialize($object);
        if (!($object instanceof DataObject)) {
            debug("Unserialized object is not DataObject");
            return;
        }

        $this->object = $object;

        $this->input->setValue($this->object->getValue());
    }

}