<?php
include_once("pages/SparkPage.php");

class BufferedPage extends SparkPage
{

    protected function constructTitle() : void
    {

    }

    /**
     * @return void
     */
    protected function headFinalize() : void
    {
        $this->head()->addMeta("keywords", "%meta_keywords%");
        $this->head()->addMeta("description", "%meta_description%");
    }

    public function obCallback(string &$buffer)
    {
        $title = $this->preferred_title;

        $meta_description = "";

        if (DB_ENABLED) {
            $config = ConfigBean::Factory();
            $config->setSection("seo");
            $meta_description = $config->get("meta_description");
        }

        if ($this->description) {
            $meta_description = $this->description;
        }

        $replace = array(
            "%title%"=> strip_tags($title),
            "%meta_description%" => prepareMeta($meta_description)
        );

        $buffer = strtr($buffer, $replace);

    }

    public function startRender(): void
    {
        $this->buffer->start();
        parent::startRender(); // TODO: Change the autogenerated stub
    }

    public function finishRender(): void
    {
        parent::finishRender();
        $this->buffer->end();
        $this->obCallback($this->buffer->data());

        echo $this->buffer->get();
    }
}
?>
