<?php
include_once("pages/SparkPage.php");

class BufferedPage extends SparkPage
{

    protected function constructTitle() : void
    {

    }
    protected function prepareMetaTitle() : void
    {

    }

    public function obCallback(string &$buffer)
    {
        $title = $this->preferred_title;

        $meta_keywords = "";
        $meta_description = "";

        if (DB_ENABLED) {
            $config = ConfigBean::Factory();
            $config->setSection("seo");

            $meta_keywords = sanitizeKeywords($config->get("meta_keywords"));
            $meta_description = $config->get("meta_description");
        }

        if ($this->keywords) {
            $meta_keywords = $this->keywords;
        }

        if ($this->description) {
            $meta_description = $this->description;
        }

        $replace = array(
            "%title%"=> strip_tags($title),
            "%meta_keywords%" => prepareMeta($meta_keywords, 150),
            "%meta_description%" => prepareMeta($meta_description, 150)
        );

        $buffer = strtr($buffer, $replace);

    }

    public function startRender()
    {
        $this->buffer->start();
        parent::startRender(); // TODO: Change the autogenerated stub
    }

    public function finishRender()
    {
        parent::finishRender();
        $this->buffer->end();
        $this->obCallback($this->buffer->data());

        echo $this->buffer->get();
    }
}
?>
