<?php
include_once("components/Container.php");
include_once("objects/IObserver.php");

class HTMLBody extends Container implements IObserver
{

    protected static ?HTMLBody $instance = null;

    public static function Instance() : HTMLBody
    {
        if (self::$instance == null) {
            self::$instance = new HTMLBody();
        }
        return self::$instance;
    }
    /**
     * @var array IPageComponent
     */
    protected array $page_components = array();

    private function __construct()
    {
        parent::__construct();
        $this->setTagName("body");
    }

    public function onEvent(SparkEvent $event): void
    {
        if (!($event instanceof ComponentEvent)) return;
        if (!$event->isEvent(ComponentEvent::COMPONENT_CREATED)) return;

        $cmp = $event->getSource();
        if (!($cmp instanceof IPageComponent)) return;

        if ($cmp instanceof IPageScript) {
            $this->page_components[] = $cmp;
        }
        else {
            if ($cmp instanceof ITemplate) {
                $template = new Template();
                $template->setID($cmp->templateID());
                $template->items()->append($cmp);
                $this->page_components[$template->getID()] = $template;
            }
            else {
                $this->page_components[get_class($cmp)] = $cmp;
            }
        }

    }

    public function finishRender(): void
    {
        foreach ($this->page_components as $idx => $cmp) {
            $cmp->render();
        }

        parent::finishRender(); // TODO: Change the autogenerated stub
    }
}