<?php
include_once("utils/DataObject.php");
include_once("utils/URLBuilder.php");

class StorageItem extends DataObject implements JsonSerializable
{

    public $id = -1;
    public $className = "";
    public $field = "";
    public $storageURL = "";

    protected $urlbuilder;

    protected $serializedURL = "";

    const TYPE_IMAGE = 1;
    const TYPE_FILE = 2;

    protected $type = StorageItem::TYPE_IMAGE;

    public function __construct(int $id = -1, string $className = "", string $field = "")
    {
        parent::__construct();

        $this->id = $id;
        $this->className = $className;
        $this->field = $field;
        $this->storageURL = STORAGE_LOCAL;

        $this->urlbuilder = new URLBuilder();
        $this->urlbuilder->buildFrom($this->storageURL);

    }

    public function setType(int $type)
    {
        $this->type = $type;
    }

    public function enableExternalURL(bool $mode)
    {
        if ($mode) {
            $this->storageURL = STORAGE_EXTERNAL;
        }
        else {
            $this->storageURL = STORAGE_LOCAL;
        }
        $this->urlbuilder->buildFrom($this->storageURL);
    }

    public function hrefImage(int $width = -1, int $height = -1)
    {
        if ($width > 0 || $height > 0) {

            if ($width == $height) {
                return $this->hrefThumb($width);
            }
            return $this->hrefCrop($width, $height);
        }
        return $this->hrefFull();
    }

    public function hrefFull()
    {
        $this->setType(StorageItem::TYPE_IMAGE);
        $this->buildURL();
        $this->urlbuilder->remove("width");
        $this->urlbuilder->remove("height");
        $this->urlbuilder->remove("size");
        return $this->urlbuilder->url();
    }

    public function hrefCrop($width, $height) : string
    {
        $this->setType(StorageItem::TYPE_IMAGE);
        $this->buildURL();
        $this->urlbuilder->remove("size");
        $this->urlbuilder->add(new URLParameter("width", $width));
        $this->urlbuilder->add(new URLParameter("height", $height));
        return $this->urlbuilder->url();

    }

    public function hrefThumb($width) : string
    {
        $this->setType(StorageItem::TYPE_IMAGE);
        $this->buildURL();
        $this->urlbuilder->remove("width");
        $this->urlbuilder->remove("height");
        $this->urlbuilder->add(new URLParameter("size", $width));
        return $this->urlbuilder->url();
    }

    public function hrefFile() : string
    {
        $this->setType(StorageItem::TYPE_FILE);
        $this->buildURL();
        return $this->urlbuilder->url();
    }

    public function href() : string
    {
        $this->buildURL();
        return $this->urlbuilder->url();
    }

    protected function buildURL()
    {
        $cmd = "image";
        if ($this->type == StorageItem::TYPE_IMAGE) {
            $cmd = "image";
        }
        else if ($this->type == StorageItem::TYPE_FILE) {
            $cmd = "data";
        }

        $this->urlbuilder->add(new URLParameter("cmd", $cmd));
        $this->urlbuilder->add(new URLParameter("class", $this->className));
        $this->urlbuilder->add(new URLParameter("id", (string)$this->id));

        if ($this->field) {
            $this->urlbuilder->add(new URLParameter("field", $this->field));
        }
    }

    public static function Create(int $id, $className)
    {
        $item = new StorageItem();
        $item->id = $id;
        if (is_object($className)) {
            $className = get_class($className);
        }
        else if (strlen($className) < 1) {
            throw new Exception("Classname required");
        }
        $item->className = $className;

        return $item;
    }

    public static function Image(int $id, $className, int $width = -1, int $height = -1)
    {
        $item = StorageItem::Create($id, $className);
        return $item->hrefImage($width, $height);
    }

    public function setData(array &$data)
    {
        parent::setData($data); // TODO: Change the autogenerated stub
        $this->id = (int)$this->value;
    }

    /**
     * Specify data which should be serialized to JSON
     * @link https://php.net/manual/en/jsonserializable.jsonserialize.php
     * @return mixed data which can be serialized by <b>json_encode</b>,
     * which is a value of any type other than a resource.
     * @since 5.4
     */
    public function jsonSerialize() : mixed
    {
        $this->serializedURL = $this->href();
        return get_object_vars($this);
    }
}

?>