<?php
include_once("utils/DataObject.php");
include_once("utils/URLBuilder.php");

class StorageItem extends DataObject
{

    public $id = -1;
    public $className = "";
    public $field = "";
    public $storageURL = "";

    protected $urlbuilder;


    public function __construct(int $id = -1, string $className = "", string $field = "")
    {
        parent::__construct();

        $this->id = $id;
        $this->className = $className;
        $this->field = $field;
        $this->storageURL = STORAGE_LOCAL;

        $this->urlbuilder = new URLBuilder();
        $this->urlbuilder->buildFrom($this->storageURL);
    }

    public function enableExternalURL(bool $mode)
    {
        if ($mode) {
            $this->storageURL = STORAGE_EXTERNAL;
        }
        else {
            $this->storageURL = STORAGE_LOCAL;
        }
        $this->urlbuilder->buildFrom($this->storageURL);
    }

    public function hrefImage(int $width = -1, int $height = -1)
    {
        if ($width > 0 || $height > 0) {

            if ($width == $height) {
                return $this->hrefThumb($width);
            }
            return $this->hrefCrop($width, $height);
        }
        return $this->hrefFull();
    }

    public function hrefFull()
    {
        $this->buildURL();
        return $this->urlbuilder->url();
    }

    public function hrefCrop($width, $height) : string
    {
        $this->buildURL();
        $this->urlbuilder->add(new URLParameter("width", $width));
        $this->urlbuilder->add(new URLParameter("height", $height));
        return $this->urlbuilder->url();

    }

    public function hrefThumb($width) : string
    {
        $this->buildURL();
        $this->urlbuilder->add(new URLParameter("size", $width));
        return $this->urlbuilder->url();
    }

    public function hrefFile() : string
    {
        $this->buildURL();
        $this->urlbuilder->get("cmd")->setValue("data");
        return $this->urlbuilder->url();
    }

    protected function buildURL()
    {
        $this->urlbuilder->add(new URLParameter("cmd", "image"));
        $this->urlbuilder->add(new URLParameter("class", $this->className));
        $this->urlbuilder->add(new URLParameter("id", (string)$this->id));

        if ($this->field) {
            $this->urlbuilder->add(new URLParameter("field", $this->field));
        }
    }

    public static function Create(int $id, $className)
    {
        $item = new StorageItem();
        $item->id = $id;
        if (is_object($className)) {
            $className = get_class($className);
        }
        else if (strlen($className) < 1) {
            throw new Exception("Classname required");
        }
        $item->className = $className;

        return $item;
    }

    public static function Image(int $id, $className, int $width = -1, int $height = -1)
    {
        $item = StorageItem::Create($id, $className);
        return $item->hrefImage($width, $height);
    }

    public function setData(array &$data)
    {
        parent::setData($data); // TODO: Change the autogenerated stub
        $this->id = (int)$this->value;
    }

}

?>