<?php

class Container extends Component
{
    protected $container;

    public function __construct()
    {
        parent::__construct();
        $this->container = array();
    }

    public function requiredScript()
    {
        return parent::requiredScript(); // TODO: Change the autogenerated stub
    }
    public function requiredStyle()
    {
        $arr =  parent::requiredStyle();
        $arr[] = SPARK_LOCAL."/css/Container.css";
        return $arr;
    }

    public function count() : int
    {
        return count($this->container);
    }

    public function clear()
    {
        $this->container = array();
    }

    public function insert(Component $cmp, int $idx)
    {
        array_splice( $this->container, $idx, 0, $cmp );
    }

    public function prepend(Component $cmp)
    {
        $this->insert($cmp , 0);
    }

    /**
     * Add component to this Container
     * @param Component $cmp
     * @return int the index position for this component
     */
    public function append(Component $cmp)
    {
        $this->container[] = $cmp;

    }

    /**
     * Return the component at index $idx
     * @param int $idx The index of the component in this container
     * @return Component
     */
    public function get(int $idx) : Component
    {
        return $this->container[$idx];
    }

    public function getByClassName(string $name) : Component
    {
        $indexes = array_keys($this->container);
        foreach ($indexes as $idx=>$index) {
            $component = $this->get($index);
            if (strcmp($name, $component->getClassName())==0) {
                return $component;
            }
        }
        throw new Exception("Component with name '$name' not found in this container");
    }

    public function findBy($callback) : Component
    {
        $indexes = array_keys($this->container);
        foreach ($indexes as $idx=>$index) {
            $component = $this->get($index);
            if ($callback($component)) {
                return $component;
            }
        }
        throw new Exception("Component not found");
    }

    public function renderImpl()
    {
        $indexes = array_keys($this->container);
        foreach ($indexes as $idx=>$index) {
            $component = $this->get($index);
            $component->render();
        }
    }


}