<?php
include_once("components/Component.php");
include_once("components/renderers/IPhotoRenderer.php");

class GalleryTape extends Component implements IPhotoRenderer
{
    /**
     * @var ImagePopup
     */
    protected $image_popup;

    /**
     * @var IDataIterator
     */
    protected $iterator;

    public function __construct()
    {
        parent::__construct();
        $this->image_popup = new ImagePopup();
        $this->image_popup->setPhotoSize(-1, 128);

    }

    public function requiredStyle(): array
    {
        $ret = parent::requiredStyle();
        $ret[] = SPARK_LOCAL . "/css/GalleryTape.css";
        return $ret;
    }

    public function requiredScript(): array
    {
        $ret = parent::requiredScript();
        $ret[] = SPARK_LOCAL . "/js/GalleryTape.js";
        return $ret;
    }

    public function getImagePoup(): ImagePopup
    {
        return $this->image_popup;
    }

    /**
     * Set the ImagePopup bean class
     * @param string $beanClass
     */
    public function setBeanClass(string $beanClass)
    {
        $this->image_popup->setBeanClass($beanClass);
    }

    public function setIterator(IDataIterator $iterator)
    {
        $this->iterator = $iterator;
    }

    /**
     * Sets the component name and set the ImagePopup relation attribute
     * @param string $name
     */
    public function setName(string $name)
    {
        parent::setName($name);
        $this->image_popup->setAttribute("relation", $name);
    }

    public function setPhotoSize(int $width, int $height)
    {
        $this->image_popup->setPhotoSize($width, $height);
    }

    public function getPhotoWidth(): int
    {
        return $this->image_popup->getPhotoWidth();
    }

    public function getPhotoHeight(): int
    {
        return $this->image_popup->getPhotoHeight();
    }

    public function startRender()
    {
        parent::startRender(); // TODO: Change the autogenerated stub

        if (!$this->image_popup->getBeanClass()) throw new Exception("Bean class not set");
        $this->iterator->exec();
    }

    protected function renderImpl()
    {

        echo "<div class='contents'>";

        echo "<div class='button left'></div>";

        echo "<div class='viewport'>";

        echo "<div class='slots'>";

        $pos = 0;

        while ($data = $this->iterator->next()) {

            echo "<div class='slot' position='$pos'>";
            $itemID = $data[$this->iterator->key()];

            $this->image_popup->setID($itemID);
            $this->image_popup->render();

            echo "</div>";
            $pos++;
        }
        echo "</div>"; //slots

        echo "</div>"; //viewport

        echo "<div class='button right' ></div>";

        echo "</div>";
    }

    public function finishRender()
    {
        parent::finishRender(); // TODO: Change the autogenerated stub
        ?>
        <script type='text/javascript'>
            onPageLoad(function () {

                let gallery_tape = new GalleryTape();
                gallery_tape.setName("<?php echo $this->getName();?>");
                gallery_tape.initialize();

            });

        </script>
        <?php
    }
}

?>