<?php
include_once("components/Component.php");
include_once("components/renderers/IPhotoRenderer.php");
include_once("components/renderers/items/DataIteratorItem.php");
include_once("components/renderers/IDataIteratorRenderer.php");

class GalleryTapeItem extends DataIteratorItem implements IPhotoRenderer
{
    protected $url;

    /**
     * @var ImagePopup
     */
    protected $image_popup;

    public function __construct()
    {
        parent::__construct();
        $this->image_popup = new ImagePopup();
        $this->image_popup->setPhotoSize(-1, 128);

        $this->url = NULL;

        $this->setComponentClass("slot");
    }

    public function setData(array &$data)
    {
        parent::setData($data);

        if ($this->url) {
            $this->url->setData($data);
        }
    }

    public function setItemURL(URLBuilder $url)
    {
        $this->url = $url;
    }

    /**
     * Set the ImagePopup bean class
     * @param string $beanClass
     */
    public function setBeanClass(string $beanClass)
    {
        $this->image_popup->setBeanClass($beanClass);
    }

    /**
     * Sets the component name and set the ImagePopup relation attribute
     * @param string $name
     */
    public function setName(string $name)
    {
        //parent::setName($name);

        $this->image_popup->setRelation($name);
    }

    public function setPhotoSize(int $width, int $height)
    {
        $this->image_popup->setPhotoSize($width, $height);
    }

    public function getPhotoWidth(): int
    {
        return $this->image_popup->getPhotoWidth();
    }

    public function getPhotoHeight(): int
    {
        return $this->image_popup->getPhotoHeight();
    }

    protected function renderImpl()
    {
        if (!$this->image_popup->getBeanClass()) throw new Exception("Bean class not set");
        if ($this->id < 1) throw new Exception("ID not set");
        if ($this->url) {
            $this->image_popup->setAttribute("href", $this->url->url());
        }
        $this->image_popup->setID($this->id);
        $this->image_popup->render();
    }
}

class GalleryTape extends Component implements IDataIteratorRenderer
{

    /**
     * @var IDataIterator
     */
    protected $iterator;

    protected $item_renderer;

    protected $default_renderer;

    public function __construct()
    {
        parent::__construct();

    }

    public function requiredStyle(): array
    {
        $ret = parent::requiredStyle();
        $ret[] = SPARK_LOCAL . "/css/GalleryTape.css";
        return $ret;
    }

    public function requiredScript(): array
    {
        $ret = parent::requiredScript();
        $ret[] = SPARK_LOCAL . "/js/GalleryTape.js";
        $ret[] = SPARK_LOCAL . "/js/SwipeListener.js";
        return $ret;
    }

    /**
     * Sets the component name and set the ImagePopup relation attribute
     * @param string $name
     */
    public function setName(string $name)
    {
        parent::setName($name);

        if (!$this->item_renderer) throw new Exception("Item renderer not set");
        $this->item_renderer->setName($name);
    }

    public function setIterator(IDataIterator $iterator)
    {
        $this->iterator = $iterator;
    }

    public function getIterator(): IDataIterator
    {
        return $this->iterator;
    }

    public function setItemRenderer(DataIteratorItem $item)
    {
        $this->item_renderer = $item;
    }

    public function getItemRenderer(): ?DataIteratorItem
    {
        return $this->item_renderer;
    }

    public function startRender()
    {
        parent::startRender(); // TODO: Change the autogenerated stub

        $this->iterator->exec();
    }

    protected function renderImpl()
    {

        echo "<div class='contents'>";

        echo "<div class='button left'></div>";

        echo "<div class='viewport'>";

        echo "<div class='slots'>";

        $pos = 0;

        while ($data = $this->iterator->next()) {

            $itemID = $data[$this->iterator->key()];

            $this->item_renderer->setAttribute("position", $pos);

            $this->item_renderer->setID($itemID);
            $this->item_renderer->setData($data);
            $this->item_renderer->render();

            $pos++;
        }
        echo "</div>"; //slots

        echo "</div>"; //viewport

        echo "<div class='button right' ></div>";

        echo "</div>";
    }

    public function finishRender()
    {
        parent::finishRender(); // TODO: Change the autogenerated stub
        ?>
        <script type='text/javascript'>
            onPageLoad(function () {

                let gallery_tape = new GalleryTape();
                gallery_tape.setName("<?php echo $this->getName();?>");
                gallery_tape.initialize();

            });

        </script>
        <?php
    }

}

?>