<?php
include_once("components/Container.php");
include_once("components/BeanFormEditor.php");

//TODO:
include_once("class/pages/AdminPage.php");

abstract class PageTemplate extends Container
{
    protected $page;
    protected $view;

    protected $request_condition;

    public function __construct()
    {
        parent::__construct();

        $this->initPage();

        $this->initPageActions();
    }

    abstract protected function initPage();

    abstract protected function initPageActions();

    abstract public function initView();

    public function processInput()
    {

    }

    public function startRender()
    {
        if (!$this->view) $this->initView();

        $this->processInput();

        $this->page->startRender();

        parent::startRender(); // TODO: Change the autogenerated stub
    }

    public function finishRender()
    {
        parent::finishRender(); // TODO: Change the autogenerated stub

        $this->page->finishRender();
    }

    public function setRequestCondition(RequestParameterCondition $request_condition)
    {
        $this->request_condition = $request_condition;
    }

    public function getRequestCondition() : RequestParameterCondition
    {
        return $this->request_condition;
    }

}